### PR TITLE
Name the transaction visual image enhancement #237

### PR DESCRIPTION
**Pull request by satishccy**
This PR adds a visual representation of transaction IDs for single transactions and includes group IDs and round numbers for grouped transaction views which i have followed from #237 . The changes aim to enhance the user interface with minimal modifications.

As a student making my first open-source contribution, I am eager to learn and improve. I welcome any feedback on the code and would greatly appreciate guidance on best practices.

### CODE REVIEW

**Comment by neilcampbell** [comment]
@satishccy Thanks for the PR. 
The issue may have been a little unclear, the main goal of this issue was to name the filename that we generate, rather than changing the image content. I'd also recommend changing the `asTransactionsGraphData` mapper function to return this information, rather than passing in the group or transaction.

**Comment by satishccy** [comment]
@neilcampbell Sorry for my confusion earlier.
I have removed the previous changes & added logic to generate filename in `asTransactionsGraphData` mapper function.

**Comment by neilcampbell** [comment]
@satishccy Awesome work! I hadn't considered that, it's a base64 encoded value so can have `/`, `+` and `=` characters. It's a little annoying, as it changes the group id. I'll have a bit of a think to see if there is another option.

**Comment by satishccy** [comment]
@neilcampbell ok, In the meanwhile can I work on any features or enhancements that are open to work on?

**Comment by neilcampbell** [comment]
@satishccy Yeah sure. You could have a go at https://github.com/algorandfoundation/algokit-lora/issues/238
I'll tag you in the comments of that issue with some extra info.

**Comment by neilcampbell** [comment]
I've had to create another PR to push a couple of additional tweaks see https://github.com/algorandfoundation/algokit-lora/pull/250. Closing this.

**Pull request closed without merging**
